[2024-04-15T00:06:07.513+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-15T00:06:07.535+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract_and_load_equipment_sensors.load_to_mysql scheduled__2022-07-06T00:00:00+00:00 [queued]>
[2024-04-15T00:06:07.547+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract_and_load_equipment_sensors.load_to_mysql scheduled__2022-07-06T00:00:00+00:00 [queued]>
[2024-04-15T00:06:07.548+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-04-15T00:06:07.570+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): load_to_mysql> on 2022-07-06 00:00:00+00:00
[2024-04-15T00:06:07.584+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1294) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-15T00:06:07.585+0000] {standard_task_runner.py:63} INFO - Started process 1335 to run task
[2024-04-15T00:06:07.585+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'extract_and_load_equipment_sensors', 'load_to_mysql', 'scheduled__2022-07-06T00:00:00+00:00', '--job-id', '470', '--raw', '--subdir', 'DAGS_FOLDER/dag_equipment_sensors.py', '--cfg-path', '/tmp/tmp_21xvq1r']
[2024-04-15T00:06:07.586+0000] {standard_task_runner.py:91} INFO - Job 470: Subtask load_to_mysql
[2024-04-15T00:06:07.645+0000] {task_command.py:426} INFO - Running <TaskInstance: extract_and_load_equipment_sensors.load_to_mysql scheduled__2022-07-06T00:00:00+00:00 [running]> on host cb5b33b73a08
[2024-04-15T00:06:07.736+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='extract_and_load_equipment_sensors' AIRFLOW_CTX_TASK_ID='load_to_mysql' AIRFLOW_CTX_EXECUTION_DATE='2022-07-06T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2022-07-06T00:00:00+00:00'
[2024-04-15T00:06:07.738+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-15T00:06:07.738+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-15T00:06:07.739+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: load_to_mysql() missing 1 required positional argument: 'df'
[2024-04-15T00:06:07.748+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_sensors, task_id=load_to_mysql, execution_date=20220706T000000, start_date=20240415T000607, end_date=20240415T000607
[2024-04-15T00:06:07.767+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 470 for task load_to_mysql (load_to_mysql() missing 1 required positional argument: 'df'; 1335)
[2024-04-15T00:06:07.799+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-15T00:06:07.822+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-15T00:06:07.827+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
