[2024-04-15T00:26:11.884+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-15T00:26:11.907+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract_and_load_equipment_sensors.load_to_mysql manual__2024-04-15T00:26:00.686476+00:00 [queued]>
[2024-04-15T00:26:11.914+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract_and_load_equipment_sensors.load_to_mysql manual__2024-04-15T00:26:00.686476+00:00 [queued]>
[2024-04-15T00:26:11.915+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-04-15T00:26:11.934+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): load_to_mysql> on 2024-04-15 00:26:00.686476+00:00
[2024-04-15T00:26:11.948+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=80) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-15T00:26:11.946+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'extract_and_load_equipment_sensors', 'load_to_mysql', 'manual__2024-04-15T00:26:00.686476+00:00', '--job-id', '2339', '--raw', '--subdir', 'DAGS_FOLDER/dag_equipment_sensors.py', '--cfg-path', '/tmp/tmp09bed1lo']
[2024-04-15T00:26:11.954+0000] {standard_task_runner.py:63} INFO - Started process 82 to run task
[2024-04-15T00:26:11.954+0000] {standard_task_runner.py:91} INFO - Job 2339: Subtask load_to_mysql
[2024-04-15T00:26:12.019+0000] {task_command.py:426} INFO - Running <TaskInstance: extract_and_load_equipment_sensors.load_to_mysql manual__2024-04-15T00:26:00.686476+00:00 [running]> on host 5844c8608a80
[2024-04-15T00:26:12.152+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='extract_and_load_equipment_sensors' AIRFLOW_CTX_TASK_ID='load_to_mysql' AIRFLOW_CTX_EXECUTION_DATE='2024-04-15T00:26:00.686476+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-15T00:26:00.686476+00:00'
[2024-04-15T00:26:12.154+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-15T00:26:12.266+0000] {logging_mixin.py:188} INFO - Erro ao inserir DataFrame na tabela equipment_sensors: (MySQLdb.OperationalError) (1054, "Unknown column 'item' in 'field list'")
[SQL: INSERT INTO equipment_sensors (item) VALUES (%s)]
[parameters: (('equipment_id,sensor_id',), ('1,4275',), ('2,5212',), ('3,7381',), ('4,396',), ('5,1645',), ('6,9532',), ('7,3328',)  ... displaying 10 of 10001 total bound parameter sets ...  ('3,5440',), ('4,3653',))]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2024-04-15T00:26:12.267+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-04-15T00:26:12.268+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-15T00:26:12.275+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=extract_and_load_equipment_sensors, task_id=load_to_mysql, execution_date=20240415T002600, start_date=20240415T002611, end_date=20240415T002612
[2024-04-15T00:26:12.330+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-15T00:26:12.343+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-15T00:26:12.346+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
