[2024-04-15T00:06:20.134+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-15T00:06:20.168+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract_and_load_equipment_sensors.load_to_mysql scheduled__2022-07-17T00:00:00+00:00 [queued]>
[2024-04-15T00:06:20.183+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract_and_load_equipment_sensors.load_to_mysql scheduled__2022-07-17T00:00:00+00:00 [queued]>
[2024-04-15T00:06:20.184+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-04-15T00:06:20.210+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): load_to_mysql> on 2022-07-17 00:00:00+00:00
[2024-04-15T00:06:20.228+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1439) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-15T00:06:20.230+0000] {standard_task_runner.py:63} INFO - Started process 1476 to run task
[2024-04-15T00:06:20.231+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'extract_and_load_equipment_sensors', 'load_to_mysql', 'scheduled__2022-07-17T00:00:00+00:00', '--job-id', '508', '--raw', '--subdir', 'DAGS_FOLDER/dag_equipment_sensors.py', '--cfg-path', '/tmp/tmp0uyxk0vg']
[2024-04-15T00:06:20.232+0000] {standard_task_runner.py:91} INFO - Job 508: Subtask load_to_mysql
[2024-04-15T00:06:20.307+0000] {task_command.py:426} INFO - Running <TaskInstance: extract_and_load_equipment_sensors.load_to_mysql scheduled__2022-07-17T00:00:00+00:00 [running]> on host cb5b33b73a08
[2024-04-15T00:06:20.436+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='extract_and_load_equipment_sensors' AIRFLOW_CTX_TASK_ID='load_to_mysql' AIRFLOW_CTX_EXECUTION_DATE='2022-07-17T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2022-07-17T00:00:00+00:00'
[2024-04-15T00:06:20.439+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-15T00:06:20.440+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-15T00:06:20.442+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: load_to_mysql() missing 1 required positional argument: 'df'
[2024-04-15T00:06:20.459+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_sensors, task_id=load_to_mysql, execution_date=20220717T000000, start_date=20240415T000620, end_date=20240415T000620
[2024-04-15T00:06:20.495+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 508 for task load_to_mysql (load_to_mysql() missing 1 required positional argument: 'df'; 1476)
[2024-04-15T00:06:20.529+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-15T00:06:20.553+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-15T00:06:20.558+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
